#!/usr/bin/env python3
'''A program that factorize as many numbers as possible
 into a product of two smaller numbers.'''
from sys import argv

''' sys for input the file that contain the numbers to be factorized
+ error handler gives a message of the usage of the program
'''

def factors(value):
    '''"print a simple descomposition of an integer sup  than 1'''
    x = 2

    if value < 2:
        return
    print()
    print(value, "<- value-bef")
    while value % x:
        x += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / x, x))
    print(value, "<- value-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factors(value)
            line = file.readline()
except:
    pass
