#!/usr/bin/env python3

''' A program that Factorize as many numbers
as possible into a product of two smaller numbers
'''


import sys

''' sys for input the file that contain the numbers to be factorized
+ error handler gives a message of the usage of the program
'''

if len(sys.argv) != 2:
    print("\nUsage : ./factors <filename>")
    sys.exit(1)
else:
    x = sys.argv[1]
''' main function that open and read the file
and factorize every single number
'''
with open(x, 'r') as file:
    for line in file:
        if line:
            for i in range(2, 9):
                if int(line) % i == 0:
                    print("{:d}={:d}*{:d}".format(int(line), int(line)//i, i))
                    break
